/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ripal
 */
public class Pertemuan5 extends javax.swing.JFrame {

    /**
     * Creates new form Pertemuan5
     */
    public Pertemuan5() {
        initComponents();
        clear();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg21 = new bg2();
        tfTugas = new javax.swing.JTextField();
        tfUTS = new javax.swing.JTextField();
        tfUAS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();
        btHitung = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlGrade = new javax.swing.JLabel();
        jlAkhir = new javax.swing.JLabel();
        jlLulus = new javax.swing.JLabel();
        jlGagal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bg21KeyPressed(evt);
            }
        });

        tfTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTugasActionPerformed(evt);
            }
        });
        tfTugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTugasKeyPressed(evt);
            }
        });

        tfUTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUTSActionPerformed(evt);
            }
        });
        tfUTS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUTSKeyPressed(evt);
            }
        });

        tfUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUASActionPerformed(evt);
            }
        });
        tfUAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUASKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nilai Tugas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nilai UTS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nilai UAS");

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        btHitung.setText("Hitung Nilai");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });
        btHitung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btHitungKeyPressed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlGrade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlGrade.setForeground(new java.awt.Color(255, 51, 51));
        jlGrade.setText("Grade");
        jPanel1.add(jlGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 99, 24));

        jlAkhir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlAkhir.setForeground(new java.awt.Color(255, 102, 0));
        jlAkhir.setText("Nilai");
        jlAkhir.setToolTipText("");
        jPanel1.add(jlAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 99, 24));

        jlLulus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/happy1.png"))); // NOI18N
        jPanel1.add(jlLulus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, 120));

        jlGagal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sad1.png"))); // NOI18N
        jlGagal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlGagalKeyPressed(evt);
            }
        });
        jPanel1.add(jlGagal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 99, 100));

        javax.swing.GroupLayout bg21Layout = new javax.swing.GroupLayout(bg21);
        bg21.setLayout(bg21Layout);
        bg21Layout.setHorizontalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg21Layout.createSequentialGroup()
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))))
                        .addGap(65, 65, 65)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg21Layout.setVerticalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg21Layout.createSequentialGroup()
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addComponent(tfTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel1))
                        .addGap(64, 64, 64)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTugasActionPerformed

    private void tfUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUTSActionPerformed

    private void tfUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUASActionPerformed

    private void tfTugasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTugasKeyPressed
        // TODO add your handling code here:
        int kode=evt.getKeyCode();
            if (kode==evt.VK_ENTER)
                tfUTS.requestFocus();
    }//GEN-LAST:event_tfTugasKeyPressed

    private void tfUASKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUASKeyPressed
        // TODO add your handling code here:
         int kode=evt.getKeyCode();
            if (kode==evt.VK_ENTER)
                btHitung.requestFocus();
    }//GEN-LAST:event_tfUASKeyPressed

    private void tfUTSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUTSKeyPressed
        // TODO add your handling code here:
         int kode=evt.getKeyCode();
            if (kode==evt.VK_ENTER)
                tfUAS.requestFocus();
    }//GEN-LAST:event_tfUTSKeyPressed

    private void bg21KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bg21KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bg21KeyPressed

    private void btHitungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btHitungKeyPressed
        // TODO add your handling code here:
        hitung();
    }//GEN-LAST:event_btHitungKeyPressed

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed
        // TODO add your handling code here:
        hitung();
    }//GEN-LAST:event_btHitungActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btClearActionPerformed

    private void jlGagalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlGagalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlGagalKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pertemuan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pertemuan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pertemuan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pertemuan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pertemuan5().setVisible(true);
            }
        });
    }
    
    public void hitung(){
        int tugas,uts,uas;
        tugas= Integer.parseInt(tfTugas.getText());
        uts= Integer.parseInt(tfUTS.getText());
        uas= Integer.parseInt(tfUAS.getText());
        
        double akhir = 0.2*tugas+0.3*uts+0.5*uas;
        jlAkhir.setText("Nilai : "+akhir);
        
        if (akhir>=88){
            jlGrade.setText("Grade A");
            jlLulus.setVisible(true);
            jlGagal.setVisible(false);
        }else if (akhir>=74){
            jlGrade.setText("Grade B");
            jlLulus.setVisible(true);
            jlGagal.setVisible(false);
        }else if (akhir>=56){
            jlGrade.setText("Grade C");
            jlLulus.setVisible(false);
            jlGagal.setVisible(true);
        }else if (akhir>=45){
            jlGrade.setText("Grade D");
            jlLulus.setVisible(false);
            jlGagal.setVisible(true);
        }else {
            jlGrade.setText("Grade E");
            jlLulus.setVisible(false);
            jlGagal.setVisible(true);
        }
    }
    
    
    public void clear(){
        tfTugas.setText("");
        tfUTS.setText("");
        tfUAS.setText("");
        jlAkhir.setText("Nilai Akhir");
        jlGrade.setText("Grade");
        jlLulus.setVisible(false);
        jlGagal.setVisible(false);
        tfTugas.requestFocus();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bg2 bg21;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlAkhir;
    private javax.swing.JLabel jlGagal;
    private javax.swing.JLabel jlGrade;
    private javax.swing.JLabel jlLulus;
    private javax.swing.JTextField tfTugas;
    private javax.swing.JTextField tfUAS;
    private javax.swing.JTextField tfUTS;
    // End of variables declaration//GEN-END:variables
}
